# Generated by Django 2.1.2 on 2019-02-05 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dog_age',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dog_gender',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dog_size',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
