# Generated by Django 2.1.5 on 2019-02-06 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190205_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dog_age',
            field=models.CharField(blank=True, default='b,y,a,s', max_length=3),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dog_gender',
            field=models.CharField(blank=True, default='m,f', max_length=8),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dog_size',
            field=models.CharField(blank=True, default='s,m,l,xl', max_length=8),
        ),
    ]
