# Generated by Django 2.1.5 on 2019-02-07 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190206_2157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='dog_age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='dog_gender',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='dog_size',
            new_name='size',
        ),
    ]
