# Generated by Django 2.1.2 on 2019-02-07 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190207_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='dog',
            name='size',
            field=models.CharField(max_length=10),
        ),
    ]
