# Generated by Django 2.1.2 on 2019-02-08 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_userdog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='age',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='dog',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
