# Generated by Django 2.1.5 on 2019-03-13 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20190313_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='color',
            field=models.CharField(blank=True, default='d,l', max_length=8),
        ),
    ]
