# Generated by Django 2.1.5 on 2019-03-14 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_profile_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='size',
            field=models.CharField(blank=True, choices=[('s', 's'), ('m', 'm'), ('l', 'l'), ('xl', 'xl')], max_length=10),
        ),
    ]
